### ISSUE TITLE
Parse-Sparkuser line 20

### ISSUE THREAD

**Issue by ghost** [andrewtchilds/PSSpark#1]
Get this error when using Get-SparkUser

Cannot convert null to type "System.DateTime".
At C:\Program Files\WindowsPowerShell\Modules\PSSpark\0.5\Private\Parse-SparkUser.ps1:20 char:9
 [PSCustomObject]@{
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast

**Comment by andrewtchilds** [comment]
Hi @darkstar939, this should be fixed in version 0.6

**Comment by ghost** [comment]
When is that coming?  I am willing to help you work on it.  I have a few functions I am working on.




On Friday, February 2, 2018, 8:56 PM, Andrew Childs <notifications@github.com> wrote:


Hi @darkstar939, this should be fixed in 0.6

**Comment by andrewtchilds** [comment]
@darkstar939, version 0.6 is out already. Should be able to just do `Update-Module -Name PSSpark`

**Comment by ghost** [comment]
On Saturday, February 3, 2018, 5:13 AM, Andrew Childs <notifications@github.com> wrote:


@darkstar939, version 0.6 is out already. Should be able to just do Update-Module -Name PSSpark

**Comment by ghost** [comment]
Disregard updated module but now command returns nothing




On Saturday, February 3, 2018, 5:13 AM, Andrew Childs <notifications@github.com> wrote:


@darkstar939, version 0.6 is out already. Should be able to just do Update-Module -Name PSSpark

**Comment by ghost** [comment]
was a TLS issue when cisco forced users to TLS 1.2
